const ActionType = { 

  APP_MOBILE: 'APP_MOBILE',
  APP_HEADER_ACTIVE_LINK: 'APP_HEADER_ACTIVE_LINK',
  APP_PAGES_SCREEN:'APP_PAGES_SCREEN',
  APP_MODAL_FULL_QUESTION_SHOW: 'APP_MODAL_FULL_QUESTION_SHOW',
  APP_MODAL_MINI_QUESTION_SHOW: 'APP_MODAL_MINI_QUESTION_SHOW',
  
  MODAL_BYER_EMAIL:'MODAL_BYER_EMAIL',
  MODAL_BYER_TEL:'MODAL_BYER_TEL',
  MODAL_BYER_FIRST_NAME:'MODAL_BYER_FIRST_NAME',
  MODAL_BYER_LAST_NAME:'MODAL_BYER_LAST_NAME',
  MODAL_BYER_PROJECTDETAIL:'MODAL_BYER_PROJECTDETAIL',
  MODAL_BYER_STREET_ADDRESS:'MODAL_BYER_STREET_ADDRESS',
  MODAL_BYER_CITY:'MODAL_BYER_CITY',
  MODAL_BYER_ZIP:'MODAL_BYER_ZIP',
  
}

export default ActionType;